### ISSUE TITLE
I need some help to improve my addEventListener lines.

### ISSUE THREAD

**Issue by sahinmeric** [sahinmeric/split-image#1]
`document.getElementById("part0").addEventListener("click", rotate);
  document.getElementById("part0").addEventListener("click", checkStatus);
  document.getElementById("part1").addEventListener("click", rotate);
  document.getElementById("part1").addEventListener("click", checkStatus);
  document.getElementById("part2").addEventListener("click", rotate);
  document.getElementById("part2").addEventListener("click", checkStatus);
  document.getElementById("part3").addEventListener("click", rotate);
  document.getElementById("part3").addEventListener("click", checkStatus);`

I want these addEventListeners created with a for loop or any other better solution. Thank you so much for any help.

**Comment by developerval** [comment]
Hi @sahinmeric - I'm happy to implement something here for you, if you're happy to assign me :) I've written up something that works in isolation, I'll implement and create a PR after work/when I get a moment this evening.

**Comment by sahinmeric** [comment]
Hi, @developerval Thank you so much for helping me, I just did some improvements recently this part of code with for each loop

`  var slicedImages = document.getElementsByClassName("sliced");

  for (let i = 0; i < slicedImages.length; i++) {
    const element = slicedImages[i];
    element.addEventListener("click", rotate, checkStatus);
  }
}`

but there are more to review and improve, feel free to contribute for any part. Thank you again!

**Comment by developerval** [comment]
@sahinmeric 
No problem! I've had a look through the file and I can see a few areas that are marked TODO and I'm happy to help :) 

Out of curiosity - have you tested the loop you've implemented? I'm not sure that you can add 2 event listeners in one addEventListener the way you've done it - I can create a PR later for an alternate solution if you'd like, then I can help with the other parts!

**Comment by sahinmeric** [comment]
I am really stucked with frontend, basically I deleted many things and creating from zero. I should have watched more CSS videos :)) 
I think you are right about adding two event listener like that. I think I just checked the first func and forget to check checkStatus one, which probably was´t already working.

**Comment by sahinmeric** [comment]
What I am trying todo now is when we slice an image to 4, 9, 16 or even 25 pieces, I want all parts to be shown 2x2, 3x3 ,4x4, 5x5 squares at the frontend.

**Comment by developerval** [comment]
Well I can definitely help with a few things that are in app.js, I'm not the best FE dev in the world but happy to try and help with the other things :) Do you have discord or slack or anything that we could use to send messages rather than using github?

**Comment by sahinmeric** [comment]
Hi, we can try discord El Shajo#5471
